/**
 * PRATIKSHYA FASHION — Admin navigation icons.
 *
 * Lucide only, matching the employee portal's approach: navigation config
 * names an icon, this map resolves it, so config files never import React.
 * Includes the keys the shared PortalSidebar uses (user, logout, chevronDown).
 */

import {
  Activity,
  ArrowLeftRight,
  BadgeCheck,
  BarChart3,
  Boxes,
  Building2,
  CalendarOff,
  ChartNoAxesCombined,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  CreditCard,
  Film,
  Image as ImageIcon,
  ImagePlay,
  Inbox,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Link2Off,
  LogOut,
  Monitor,
  Package,
  PackageCheck,
  RefreshCw,
  RotateCcw,
  Settings,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Tag,
  Tags,
  Target,
  TrendingUp,
  TriangleAlert,
  Truck,
  User,
  Users,
  UsersRound,
  Video,
  Warehouse,
  Camera,
  ChevronDown,
  ChevronRight,
  Box,
} from "lucide-react";

export const ADMIN_NAV_ICONS = {
  layout: LayoutDashboard,
  camera: Camera,
  check: ClipboardCheck,
  sparkles: Sparkles,
  grid: LayoutGrid,
  layers: Layers,
  tag: Tag,
  tags: Tags,
  bag: ShoppingBag,
  users: Users,
  usersRound: UsersRound,
  undo: RotateCcw,
  boxes: Boxes,
  box: Box,
  warehouse: Warehouse,
  swap: ArrowLeftRight,
  arrowLeftRight: ArrowLeftRight,
  badge: BadgeCheck,
  shield: ShieldCheck,
  clock: Clock3,
  target: Target,
  trend: TrendingUp,
  chart: BarChart3,
  chartNoAxes: ChartNoAxesCombined,
  list: ClipboardList,
  image: ImageIcon,
  imagePlay: ImagePlay,
  film: Film,
  video: Video,
  sliders: SlidersHorizontal,
  package: Package,
  packageCheck: PackageCheck,
  inbox: Inbox,
  alert: TriangleAlert,
  alertTriangle: TriangleAlert,
  activity: Activity,
  settings: Settings,
  user: User,
  logout: LogOut,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  // Workforce additions
  calendarOff: CalendarOff,
  monitor: Monitor,
  linkSlash: Link2Off,
  // Inventory additions
  building2: Building2,
  truck: Truck,
  // Payments
  creditCard: CreditCard,
  refreshCw: RefreshCw,
};

export const adminNavIcon = (name) => ADMIN_NAV_ICONS[name] ?? LayoutDashboard;

export default ADMIN_NAV_ICONS;
