import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import AdminPage from "../../../components/admin/AdminPage";
import { apiAdminGetInvoice, apiAdminGetOrder } from "../../../services/api/ordersApi";
import { AtelierButton, Rule } from "../../../design-system";
import { formatINR } from "../../../utils/shopping";
import { formatOrderDate } from "../../../utils/orders";
import { formatPhone } from "../../../utils/validation";
import { getPaymentStatus } from "../../../config/orderConfig";

function Row({ label, value, strong = false }) {
  return (
    <div className="flex items-baseline justify-between gap-4">
      <dt className="font-ui text-[11px] text-graphite">{label}</dt>
      <dd className={strong ? "font-display text-lg font-light text-ink" : "font-ui text-xs text-ink"}>{value}</dd>
    </div>
  );
}

/**
 * Admin invoice view — /admin/orders/:orderId/invoice.
 *
 * PHASE 3: this now reads the order and its invoice metadata from the
 * backend (`GET /admin/orders/{id}` + `GET /admin/orders/{id}/invoice`)
 * instead of a synchronously-read local record whose `invoice.number` was
 * fabricated client-side. It also has real loading and error states — it
 * previously rendered "Invoice not found" while the data was still
 * undefined, and for genuine server failures alike.
 *
 * No invoice document is generated by this system: there is no PDF
 * pipeline and no stored file, so "Print / PDF" is the browser's own
 * print of this page. When no invoice number has been issued the page
 * says so rather than showing an invented one.
 */
export default function AdminOrderInvoice() {
  const { orderId } = useParams();

  const [order, setOrder] = useState(null);
  const [invoice, setInvoice] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [reloadToken, setReloadToken] = useState(0);
  const reload = useCallback(() => setReloadToken((t) => t + 1), []);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    Promise.all([apiAdminGetOrder(orderId), apiAdminGetInvoice(orderId)]).then(
      ([orderResult, invoiceResult]) => {
        if (cancelled) return;
        setLoading(false);
        if (!orderResult.ok) {
          setOrder(null);
          setError({ status: orderResult.status, message: orderResult.error });
          return;
        }
        setOrder(orderResult.order);
        setInvoice(invoiceResult.ok ? invoiceResult.invoice : null);
      }
    );
    return () => { cancelled = true; };
  }, [orderId, reloadToken]);

  if (loading) {
    return (
      <AdminPage eyebrow="Orders" title="Loading invoice…">
        <p role="status" aria-live="polite" aria-busy="true" className="font-ui text-sm text-taupe">
          Loading invoice…
        </p>
      </AdminPage>
    );
  }

  if (error || !order) {
    const status = error?.status ?? 404;
    const title =
      status === 401 ? "Session expired"
        : status === 403 ? "Not permitted"
        : status === 404 ? "Order not found"
        : "Could not load this invoice";
    const detail =
      status === 401 ? "Your admin session has expired. Sign in again to continue."
        : status === 403 ? "Your role does not include permission to view order invoices."
        : status === 404 ? "No order exists with this reference."
        : error?.message ?? "Something went wrong on our side. Please try again.";
    return (
      <AdminPage eyebrow="Orders" title={title}>
        <p role="alert" className="font-ui text-sm text-graphite">{detail}</p>
        <div className="mt-5 flex flex-wrap items-center gap-3">
          {status >= 500 || status === 0 ? (
            <AtelierButton type="button" variant="outline" size="chip" onClick={reload}>
              Try again
            </AtelierButton>
          ) : null}
          <Link to="/admin/orders" className="font-ui text-sm text-brass hover:text-accent">
            Back to orders
          </Link>
        </div>
      </AdminPage>
    );
  }

  const payment = getPaymentStatus(order.paymentStatus);
  const address = order.address;
  const invoiceNumber = invoice?.number ?? order.invoice?.number ?? null;
  const invoiceIssuedAt = invoice?.issuedAt ?? order.invoice?.issuedAt ?? null;
  const invoiceIssued = Boolean(invoiceNumber);
  const orderRef = order.orderNumber ?? order.id;

  return (
    <AdminPage
      eyebrow={`Orders / ${orderRef}`}
      title={invoiceIssued ? `Invoice · ${invoiceNumber}` : `Order summary · ${orderRef}`}
      description={
        invoiceIssued
          ? "Rendered from the order record. No invoice document is stored — use browser Print to PDF."
          : "No invoice number has been issued for this order. This is a summary of the order record."
      }
      actions={
        <>
          <AtelierButton variant="outline" size="chip" onClick={() => window.print()}>
            Print / PDF
          </AtelierButton>
          <AtelierButton as={Link} to={`/admin/orders/${order.id}`} variant="outline" size="chip">
            Back to order
          </AtelierButton>
        </>
      }
    >
      <div className="mx-auto max-w-3xl border border-mist bg-ivory px-6 py-8 sm:px-10 sm:py-12">
        <div className="flex flex-wrap items-start justify-between gap-6">
          <div>
            <h2 className="font-display text-2xl font-light tracking-[.08em] text-ink">PRATIKSHYA FASHON</h2>
            <p className="mt-1 font-ui text-[10px] uppercase tracking-[.24em] text-brass">Atelier of Handcrafted Indian Couture</p>
          </div>
          <div className="text-left sm:text-right">
            <p className="font-ui text-[10px] uppercase tracking-[.2em] text-taupe">{invoiceIssued ? "Invoice" : "Order Summary"}</p>
            <p className="mt-1 font-display text-lg font-light text-ink">{invoiceIssued ? invoiceNumber : orderRef}</p>
            <p className="mt-1 font-ui text-[11px] text-taupe">{invoiceIssuedAt ? formatOrderDate(invoiceIssuedAt) : "No invoice issued yet"}</p>
          </div>
        </div>

        <Rule width="w-full" tone="accent" className="my-7" />

        <div className="grid gap-7 sm:grid-cols-2">
          <div>
            <p className="font-ui text-[10px] uppercase tracking-[.2em] text-accent">Billed To</p>
            <p className="mt-2.5 font-display text-base font-light text-ink">{order.customer.fullName}</p>
            <p className="font-ui text-xs text-graphite">{order.customer.email}</p>
            {order.customer.phone && <p className="font-ui text-xs text-graphite">{formatPhone(order.customer.phone)}</p>}
          </div>
          {address && (
            <div>
              <p className="font-ui text-[10px] uppercase tracking-[.2em] text-accent">Delivered To</p>
              <p className="mt-2.5 font-display text-base font-light text-ink">{address.fullName}</p>
              <p className="font-ui text-xs leading-relaxed text-graphite">{address.addressLine}{address.landmark ? `, ${address.landmark}` : ""}</p>
              <p className="font-ui text-xs text-graphite">{address.city}, {address.state} — {address.pincode}</p>
            </div>
          )}
        </div>

        <div className="mt-8 grid gap-4 border border-mist/80 bg-surface/30 p-5 sm:grid-cols-3">
          <div><p className="font-ui text-[10px] uppercase tracking-[.2em] text-taupe">Order ID</p><p className="mt-1 font-ui text-sm text-ink">{orderRef}</p></div>
          <div><p className="font-ui text-[10px] uppercase tracking-[.2em] text-taupe">Order Date</p><p className="mt-1 font-ui text-sm text-ink">{formatOrderDate(order.createdAt)}</p></div>
          <div><p className="font-ui text-[10px] uppercase tracking-[.2em] text-taupe">Payment</p><p className="mt-1 font-ui text-sm text-ink">{order.paymentMethod.label} · {payment.label}</p></div>
        </div>

        <table className="mt-8 w-full border-collapse text-left">
          <thead>
            <tr className="border-b border-ink/20">
              <th className="pb-3 font-ui text-[10px] uppercase tracking-[.2em] text-taupe">Piece</th>
              <th className="pb-3 text-center font-ui text-[10px] uppercase tracking-[.2em] text-taupe">Qty</th>
              <th className="pb-3 text-right font-ui text-[10px] uppercase tracking-[.2em] text-taupe">Amount</th>
            </tr>
          </thead>
          <tbody>
            {order.items.map((item) => (
              <tr key={item.lineId} className="border-b border-mist/70">
                <td className="py-3.5 pr-4">
                  <p className="font-display text-base font-light text-ink">{item.name}</p>
                  <p className="mt-0.5 font-ui text-[10px] uppercase tracking-[.14em] text-taupe">{[item.color, item.size].filter(Boolean).join(" · ") || "Free Size"}</p>
                </td>
                <td className="py-3.5 text-center font-ui text-xs text-graphite">{item.quantity}</td>
                <td className="py-3.5 text-right font-ui text-xs text-ink">{formatINR(item.lineTotal)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="mt-7 flex justify-end">
          <dl className="w-full space-y-2.5 sm:max-w-xs">
            <Row label="Subtotal" value={formatINR(order.pricing.subtotal)} />
            {order.pricing.productDiscount > 0 && <Row label="Product discount" value={`− ${formatINR(order.pricing.productDiscount)}`} />}
            {order.pricing.couponDiscount > 0 && <Row label={`Offer · ${order.pricing.couponCode ?? "Applied"}`} value={`− ${formatINR(order.pricing.couponDiscount)}`} />}
            <Row label="Delivery" value={order.pricing.shipping === 0 ? "Complimentary" : formatINR(order.pricing.shipping)} />
            {order.pricing.codFee > 0 && <Row label="Cash on delivery fee" value={formatINR(order.pricing.codFee)} />}
            <div className="border-t border-ink/20 pt-3"><Row label="Total" value={formatINR(order.pricing.total)} strong /></div>
          </dl>
        </div>

        <Rule width="w-full" tone="accent" className="my-8" />
        <p className="font-ui text-[10px] uppercase leading-relaxed tracking-[.16em] text-taupe">{invoiceIssued ? "Rendered from the PRATIKSHYA FASHON order record. Not a tax invoice — no tax is charged or recorded on this order." : "No invoice has been issued for this order. This is a summary of the order record, not a tax invoice."}</p>
      </div>
    </AdminPage>
  );
}
