/**
 * PRATIKSHYA FASHON — Employee roles.
 *
 * Role identifiers never appear as raw strings in JSX. Each role owns a
 * default permission set. Custom permissions may be granted later by
 * Admin without changing the role itself.
 */

import { PERMISSIONS as P } from "./employeePermissions";

export const ROLES = {
  STORE_MANAGER: "STORE_MANAGER",
  SALES_EXECUTIVE: "SALES_EXECUTIVE",
  INVENTORY_MANAGER: "INVENTORY_MANAGER",
  INVENTORY_STAFF: "INVENTORY_STAFF",
  WAREHOUSE_STAFF: "WAREHOUSE_STAFF",
  CUSTOMER_SUPPORT: "CUSTOMER_SUPPORT",
  FASHION_STYLIST: "FASHION_STYLIST",
};

export const ROLE_DEFINITIONS = {
  [ROLES.STORE_MANAGER]: {
    id: ROLES.STORE_MANAGER,
    label: "Store Manager",
    shortLabel: "Manager",
    description: "Floor leadership across sales, customers, inventory visibility and team.",
    idPrefix: "MGR",
    portal: "Store leadership",
    defaultPermissions: [
      P.DASHBOARD_VIEW,
      P.PRODUCTS_VIEW,
      P.PRODUCTS_MANAGE,
      P.CATEGORIES_VIEW,
      P.CATEGORIES_CREATE,
      P.CATEGORIES_EDIT,
      P.CATEGORIES_ARCHIVE,
      P.COLLECTIONS_VIEW,
      P.COLLECTIONS_CREATE,
      P.COLLECTIONS_EDIT,
      P.COLLECTIONS_ASSIGN,
      P.COLLECTIONS_ARCHIVE,
      P.ORDERS_VIEW,
      P.ORDERS_MANAGE,
      P.ORDERS_FULFILL,
      P.ORDERS_PICK,
      P.ORDERS_PACK,
      P.ORDERS_DISPATCH,
      P.ORDERS_CANCEL,
      P.ORDERS_RETURN,
      P.ORDERS_REFUND,
      P.CUSTOMERS_VIEW,
      P.INVENTORY_VIEW,
      P.INVENTORY_RECEIVE,
      P.INVENTORY_ADJUST,
      P.INVENTORY_TRANSFER,
      P.INVENTORY_AUDIT,
      P.RETURNS_VIEW,
      P.RETURNS_MANAGE,
      P.OFFERS_VIEW,
      P.OFFERS_CREATE,
      P.OFFERS_EDIT,
      P.OFFERS_ACTIVATE,
      P.OFFERS_PAUSE,
      P.MEDIA_VIEW,
      P.MEDIA_UPLOAD,
      P.MEDIA_EDIT,
      P.MEDIA_ASSIGN,
      P.MEDIA_MANAGE,
      P.ANALYTICS_VIEW,
      P.ANALYTICS_SALES,
      P.ANALYTICS_PRODUCTS,
      P.ANALYTICS_CUSTOMERS,
      P.ANALYTICS_INVENTORY,
      P.ANALYTICS_RETURNS,
      P.ANALYTICS_OFFERS,
      P.ANALYTICS_EMPLOYEES,
      P.PROFILE_VIEW,
      P.PROFILE_EDIT,
      P.ATTENDANCE_VIEW,
      P.ATTENDANCE_CHECKIN,
      P.ATTENDANCE_CHECKOUT,
      P.ATTENDANCE_MANAGE,
      P.ATTENDANCE_CORRECT,
      P.LEAVE_VIEW,
      P.LEAVE_CREATE,
      P.LEAVE_APPROVE,
      P.LEAVE_REJECT,
      P.LEAVE_MANAGE,
      P.PERFORMANCE_VIEW,
      P.PERFORMANCE_REVIEW,
      P.PERFORMANCE_MANAGE,
      P.TEAM_VIEW,
      P.SUPPORT_VIEW,
      P.STYLING_VIEW,
      P.WAREHOUSE_VIEW,
      P.WAREHOUSE_PICK,
    ],
  },
  [ROLES.SALES_EXECUTIVE]: {
    id: ROLES.SALES_EXECUTIVE,
    label: "Sales Executive",
    shortLabel: "Sales",
    description: "Assisted shopping, customer care on the floor, and order creation.",
    idPrefix: "SLS",
    portal: "Sales floor",
    defaultPermissions: [
      P.DASHBOARD_VIEW,
      P.PRODUCTS_VIEW,
      P.CATEGORIES_VIEW,
      P.COLLECTIONS_VIEW,
      P.ORDERS_VIEW,
      P.ORDERS_CREATE,
      P.CUSTOMERS_VIEW,
      P.OFFERS_VIEW,
      P.INVENTORY_VIEW,
      P.PROFILE_VIEW,
      P.PROFILE_EDIT,
      P.ATTENDANCE_VIEW,
      P.ATTENDANCE_CHECKIN,
      P.ATTENDANCE_CHECKOUT,
      P.LEAVE_VIEW,
      P.LEAVE_CREATE,
      P.PERFORMANCE_VIEW,
    ],
  },
  [ROLES.INVENTORY_MANAGER]: {
    id: ROLES.INVENTORY_MANAGER,
    label: "Inventory Manager",
    shortLabel: "Inventory",
    description: "Stock health, receiving, adjustments, transfers and inventory reports.",
    idPrefix: "INV",
    portal: "Inventory",
    defaultPermissions: [
      P.DASHBOARD_VIEW,
      P.PRODUCTS_VIEW,
      P.CATEGORIES_VIEW,
      P.COLLECTIONS_VIEW,
      P.INVENTORY_VIEW,
      P.INVENTORY_RECEIVE,
      P.INVENTORY_ADJUST,
      P.INVENTORY_TRANSFER,
      P.INVENTORY_MANAGE,
      P.INVENTORY_AUDIT,
      P.WAREHOUSE_VIEW,
      P.MEDIA_VIEW,
      P.ANALYTICS_VIEW,
      P.ANALYTICS_INVENTORY,
      P.ANALYTICS_PRODUCTS,
      P.ORDERS_VIEW,
      P.ORDERS_FULFILL,
      P.PROFILE_VIEW,
      P.PROFILE_EDIT,
      P.ATTENDANCE_VIEW,
      P.ATTENDANCE_CHECKIN,
      P.ATTENDANCE_CHECKOUT,
      P.LEAVE_VIEW,
      P.LEAVE_CREATE,
      P.PERFORMANCE_VIEW,
      P.TEAM_VIEW,
    ],
  },
  [ROLES.INVENTORY_STAFF]: {
    id: ROLES.INVENTORY_STAFF,
    label: "Inventory Staff",
    shortLabel: "Stock",
    description: "Receive, adjust and raise transfer requests on the floor.",
    idPrefix: "INV",
    portal: "Stock desk",
    defaultPermissions: [
      P.DASHBOARD_VIEW,
      P.PRODUCTS_VIEW,
      P.CATEGORIES_VIEW,
      P.COLLECTIONS_VIEW,
      P.INVENTORY_VIEW,
      P.INVENTORY_RECEIVE,
      P.INVENTORY_ADJUST,
      P.INVENTORY_TRANSFER,
      P.INVENTORY_AUDIT,
      P.PROFILE_VIEW,
      P.PROFILE_EDIT,
      P.ATTENDANCE_VIEW,
      P.ATTENDANCE_CHECKIN,
      P.ATTENDANCE_CHECKOUT,
      P.LEAVE_VIEW,
      P.LEAVE_CREATE,
      P.PERFORMANCE_VIEW,
    ],
  },
  [ROLES.WAREHOUSE_STAFF]: {
    id: ROLES.WAREHOUSE_STAFF,
    label: "Warehouse Staff",
    shortLabel: "Warehouse",
    description: "Incoming, outgoing, pick & pack, transfers and damaged stock.",
    idPrefix: "WHS",
    portal: "Warehouse",
    defaultPermissions: [
      P.DASHBOARD_VIEW,
      P.WAREHOUSE_VIEW,
      P.WAREHOUSE_PICK,
      P.PRODUCTS_VIEW,
      P.CATEGORIES_VIEW,
      P.COLLECTIONS_VIEW,
      P.INVENTORY_VIEW,
      P.INVENTORY_RECEIVE,
      P.INVENTORY_TRANSFER,
      P.INVENTORY_AUDIT,
      P.MEDIA_VIEW,
      P.ORDERS_VIEW,
      P.ORDERS_FULFILL,
      P.ORDERS_PICK,
      P.ORDERS_PACK,
      P.ORDERS_DISPATCH,
      P.PROFILE_VIEW,
      P.PROFILE_EDIT,
      P.ATTENDANCE_VIEW,
      P.ATTENDANCE_CHECKIN,
      P.ATTENDANCE_CHECKOUT,
      P.LEAVE_VIEW,
      P.LEAVE_CREATE,
      P.PERFORMANCE_VIEW,
    ],
  },
  [ROLES.CUSTOMER_SUPPORT]: {
    id: ROLES.CUSTOMER_SUPPORT,
    label: "Customer Support",
    shortLabel: "Support",
    description: "Customer care, orders, returns and feedback.",
    idPrefix: "CS",
    portal: "Customer care",
    defaultPermissions: [
      P.DASHBOARD_VIEW,
      P.CUSTOMERS_VIEW,
      P.ORDERS_VIEW,
      P.ORDERS_CANCEL,
      P.ORDERS_RETURN,
      P.ORDERS_REFUND,
      P.RETURNS_VIEW,
      P.RETURNS_MANAGE,
      P.SUPPORT_VIEW,
      P.SUPPORT_MANAGE,
      P.OFFERS_VIEW,
      P.PRODUCTS_VIEW,
      P.CATEGORIES_VIEW,
      P.COLLECTIONS_VIEW,
      P.INVENTORY_VIEW,
      P.PROFILE_VIEW,
      P.PROFILE_EDIT,
      P.ATTENDANCE_VIEW,
      P.ATTENDANCE_CHECKIN,
      P.ATTENDANCE_CHECKOUT,
      P.LEAVE_VIEW,
      P.LEAVE_CREATE,
      P.PERFORMANCE_VIEW,
      P.ANALYTICS_VIEW,
      P.ANALYTICS_CUSTOMERS,
      P.ANALYTICS_RETURNS,
    ],
  },
  [ROLES.FASHION_STYLIST]: {
    id: ROLES.FASHION_STYLIST,
    label: "Fashion Stylist",
    shortLabel: "Stylist",
    description: "Consultations, appointments, recommendations and bridal styling.",
    idPrefix: "STY",
    portal: "Atelier styling",
    defaultPermissions: [
      P.DASHBOARD_VIEW,
      P.CUSTOMERS_VIEW,
      P.PRODUCTS_VIEW,
      P.CATEGORIES_VIEW,
      P.COLLECTIONS_VIEW,
      P.STYLING_VIEW,
      P.STYLING_MANAGE,
      P.MEDIA_VIEW,
      P.MEDIA_UPLOAD,
      P.OFFERS_VIEW,
      P.INVENTORY_VIEW,
      P.PROFILE_VIEW,
      P.PROFILE_EDIT,
      P.ATTENDANCE_VIEW,
      P.ATTENDANCE_CHECKIN,
      P.ATTENDANCE_CHECKOUT,
      P.LEAVE_VIEW,
      P.LEAVE_CREATE,
      P.PERFORMANCE_VIEW,
    ],
  },
};

export const ROLE_OPTIONS = Object.values(ROLE_DEFINITIONS);

export const getRole = (roleId) =>
  ROLE_DEFINITIONS[roleId] ?? {
    id: roleId || "UNKNOWN",
    label: "Unassigned role",
    shortLabel: "Unassigned",
    description: "This role is not recognised.",
    idPrefix: "EMP",
    portal: "Employee portal",
    defaultPermissions: [P.DASHBOARD_VIEW, P.PROFILE_VIEW],
  };

export const getRoleLabel = (roleId) => getRole(roleId).label;

export const getDefaultPermissions = (roleId) => [...getRole(roleId).defaultPermissions];

export const isKnownRole = (roleId) => Boolean(ROLE_DEFINITIONS[roleId]);

export default {
  ROLES,
  ROLE_DEFINITIONS,
  ROLE_OPTIONS,
  getRole,
  getRoleLabel,
  getDefaultPermissions,
  isKnownRole,
};
