import {
  AlertTriangle,
  ArrowLeftRight,
  BadgeCheck,
  BarChart3,
  Box,
  Boxes,
  Calendar,
  CalendarDays,
  ChartNoAxesCombined,
  ChevronDown,
  ChevronRight,
  Clock3,
  FileBarChart,
  Film,
  Gem,
  HandHelping,
  Headphones,
  Image as ImageIcon,
  Inbox,
  LayoutDashboard,
  LogOut,
  Menu,
  Package,
  Plus,
  RotateCcw,
  Shirt,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Tag,
  Target,
  TrendingUp,
  Truck,
  User,
  UserRoundPlus,
  Users,
  Warehouse,
  Wand2,
  X,
} from "lucide-react";

/**
 * PRATIKSHYA FASHON — Employee navigation icon map.
 *
 * Icons come from the project's single icon dependency (lucide-react).
 * Keys here are referenced by the employee navigation configuration. The
 * icon is decorative when a label is present, so it is always aria-hidden.
 */
export const NAV_ICONS = {
  layout: LayoutDashboard,
  image: ImageIcon,
  film: Film,
  sparkles: Sparkles,
  users: Users,
  bag: ShoppingBag,
  plus: Plus,
  tag: Tag,
  boxes: Boxes,
  box: Box,
  swap: ArrowLeftRight,
  truck: Truck,
  alert: AlertTriangle,
  inbox: Inbox,
  sliders: SlidersHorizontal,
  warehouse: Warehouse,
  package: Package,
  undo: RotateCcw,
  headset: Headphones,
  wand: Wand2,
  shirt: Shirt,
  calendar: Calendar,
  calendarDays: CalendarDays,
  gem: Gem,
  trend: TrendingUp,
  team: Users,
  chart: BarChart3,
  fileBarChart: FileBarChart,
  chartNoAxes: ChartNoAxesCombined,
  badge: BadgeCheck,
  target: Target,
  clock: Clock3,
  user: User,
  userPlus: UserRoundPlus,
  handHelping: HandHelping,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  logout: LogOut,
  menu: Menu,
  close: X,
};

export const navIcon = (name) => NAV_ICONS[name] ?? LayoutDashboard;
